### ISSUE TITLE
Generator names don't follow Scala convention

### ISSUE THREAD

**Issue by noelwelsh** [japgolly/nyaya#2]
Generators like `choosedouble` clearly don't follow the Scala camel case convention. It should be `chooseDouble` etc. I know this is inherited from NICTA's rng, but I think propagating their error is a mistake.

**Comment by japgolly** [comment]
Temporarily on hold. Let's think about this a bit later.

**Comment by japgolly** [comment]
I thought. I agree. This will be done in a possibly-next major version.
