### ISSUE TITLE
Publish nyaya for scala 2.13.0

### ISSUE THREAD

**Issue by FabioPinheiro** [japgolly/nyaya#52]
This is blocking https://github.com/japgolly/scalajs-react/issues/556

japgolly/scalajs-react depend on japgolly/nyaya

**Comment by japgolly** [comment]
FYI this is nearly finished in #50

**Comment by nafg** [comment]
#50 was merged over a month ago, is there a reason this is still open?

**Comment by FabioPinheiro** [comment]
The PR https://github.com/japgolly/scalajs-react/pull/559 is still not finish
We are mainly blocked by https://github.com/scala/bug/issues/11660

**Comment by nafg** [comment]
Right but that depends on this, not the other way around. This ticket is for nyaya which was done, no?

**Comment by FabioPinheiro** [comment]
@nafg You are completely right
I believe is already publish on maven as 0.9.0-RC1
Closing this ticket
